//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Software.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Arabic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Arabic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS_Software.Globalization.Arabic", typeof(Arabic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المبيعات.
        /// </summary>
        internal static string brnSaleDetail {
            get {
                return ResourceManager.GetString("brnSaleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة الزبون.
        /// </summary>
        internal static string btnAddCustomer {
            get {
                return ResourceManager.GetString("btnAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مندوب.
        /// </summary>
        internal static string btnAddVendor {
            get {
                return ResourceManager.GetString("btnAddVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الوحدة.
        /// </summary>
        internal static string BtnAssignUnits {
            get {
                return ResourceManager.GetString("BtnAssignUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بين.
        /// </summary>
        internal static string btnBetween {
            get {
                return ResourceManager.GetString("btnBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يلغي.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واضح.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بإعداد متجرك.
        /// </summary>
        internal static string btnCreateStore {
            get {
                return ResourceManager.GetString("btnCreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء المستخدم.
        /// </summary>
        internal static string btnCreateUser {
            get {
                return ResourceManager.GetString("btnCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يحرر.
        /// </summary>
        internal static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخرج.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجد.
        /// </summary>
        internal static string btnFind {
            get {
                return ResourceManager.GetString("btnFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الفاتورة.
        /// </summary>
        internal static string btnInvoiceDetail {
            get {
                return ResourceManager.GetString("btnInvoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناصر الباركود.
        /// </summary>
        internal static string btnItemsBarcode {
            get {
                return ResourceManager.GetString("btnItemsBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الفرعي للعناصر.
        /// </summary>
        internal static string btnItemsCategory {
            get {
                return ResourceManager.GetString("btnItemsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف العناصر.
        /// </summary>
        internal static string btnItemsdefinition {
            get {
                return ResourceManager.GetString("btnItemsdefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد حجم العنصر.
        /// </summary>
        internal static string btnItemsSize {
            get {
                return ResourceManager.GetString("btnItemsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد نوع العناصر.
        /// </summary>
        internal static string btnItemsType {
            get {
                return ResourceManager.GetString("btnItemsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف وحدة العناصر.
        /// </summary>
        internal static string btnItemsUnit {
            get {
                return ResourceManager.GetString("btnItemsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        internal static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل العناصر.
        /// </summary>
        internal static string btnRptItemsDetail {
            get {
                return ResourceManager.GetString("btnRptItemsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة بيع جديدة.
        /// </summary>
        internal static string btnSales {
            get {
                return ResourceManager.GetString("btnSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرجاع فاتورة المبيعات.
        /// </summary>
        internal static string btnSalesReturns {
            get {
                return ResourceManager.GetString("btnSalesReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الحجم.
        /// </summary>
        internal static string btnSizeAssign {
            get {
                return ResourceManager.GetString("btnSizeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة مخزونك.
        /// </summary>
        internal static string BtnStock {
            get {
                return ResourceManager.GetString("BtnStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المخزون.
        /// </summary>
        internal static string btnStockDetail {
            get {
                return ResourceManager.GetString("btnStockDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخزون بالتفصيل.
        /// </summary>
        internal static string btnStockInDetail {
            get {
                return ResourceManager.GetString("btnStockInDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخزون من التفاصيل.
        /// </summary>
        internal static string btnStockOutDetail {
            get {
                return ResourceManager.GetString("btnStockOutDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم.
        /// </summary>
        internal static string btnToday {
            get {
                return ResourceManager.GetString("btnToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد دور المستخدم.
        /// </summary>
        internal static string btnUserRole {
            get {
                return ResourceManager.GetString("btnUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امس.
        /// </summary>
        internal static string btnYesterday {
            get {
                return ResourceManager.GetString("btnYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشيط.
        /// </summary>
        internal static string CkEActive {
            get {
                return ResourceManager.GetString("CkEActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معباه.
        /// </summary>
        internal static string CkEIsPacked {
            get {
                return ResourceManager.GetString("CkEIsPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشأ من قبل.
        /// </summary>
        internal static string Created_By {
            get {
                return ResourceManager.GetString("Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف العميل.
        /// </summary>
        internal static string frmCustomerDeffination {
            get {
                return ResourceManager.GetString("frmCustomerDeffination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعريف الصنف.
        /// </summary>
        internal static string frmItems_Deffination {
            get {
                return ResourceManager.GetString("frmItems_Deffination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة الشراء.
        /// </summary>
        internal static string frmPurchaseInvoices {
            get {
                return ResourceManager.GetString("frmPurchaseInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة البيع.
        /// </summary>
        internal static string frmSalesInvoices {
            get {
                return ResourceManager.GetString("frmSalesInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الحجم.
        /// </summary>
        internal static string frmSizAssigns {
            get {
                return ResourceManager.GetString("frmSizAssigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بإعداد متجرك.
        /// </summary>
        internal static string frmStore_Deffination {
            get {
                return ResourceManager.GetString("frmStore_Deffination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الفرعي.
        /// </summary>
        internal static string frmSubtype {
            get {
                return ResourceManager.GetString("frmSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        internal static string frmTypes {
            get {
                return ResourceManager.GetString("frmTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الوحدة.
        /// </summary>
        internal static string frmUnitAssign {
            get {
                return ResourceManager.GetString("frmUnitAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        internal static string frmUnits {
            get {
                return ResourceManager.GetString("frmUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق الدفع.
        /// </summary>
        internal static string gPaymentBox {
            get {
                return ResourceManager.GetString("gPaymentBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الإجمالي.
        /// </summary>
        internal static string Grand_Total {
            get {
                return ResourceManager.GetString("Grand_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الفاتورة.
        /// </summary>
        internal static string Invoice_Date {
            get {
                return ResourceManager.GetString("Invoice_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية.
        /// </summary>
        internal static string Item_Amount {
            get {
                return ResourceManager.GetString("Item_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باركود.
        /// </summary>
        internal static string Item_Barcode {
            get {
                return ResourceManager.GetString("Item_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصنف.
        /// </summary>
        internal static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الوحدة.
        /// </summary>
        internal static string Item_Sale_Price {
            get {
                return ResourceManager.GetString("Item_Sale_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين الحجم.
        /// </summary>
        internal static string lblAssignSize {
            get {
                return ResourceManager.GetString("lblAssignSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدة التخصيص.
        /// </summary>
        internal static string lblAssignUnit {
            get {
                return ResourceManager.GetString("lblAssignUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرصيد.
        /// </summary>
        internal static string lblBalance {
            get {
                return ResourceManager.GetString("lblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الباقة / الباقة:.
        /// </summary>
        internal static string lblBundlePrice {
            get {
                return ResourceManager.GetString("lblBundlePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشيك / البطاقة.
        /// </summary>
        internal static string lblCardNo {
            get {
                return ResourceManager.GetString("lblCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التصنيف.
        /// </summary>
        internal static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الخلوي.
        /// </summary>
        internal static string lblCellNo {
            get {
                return ResourceManager.GetString("lblCellNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        internal static string lblCodeNo {
            get {
                return ResourceManager.GetString("lblCodeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الزبون.
        /// </summary>
        internal static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء العناصر.
        /// </summary>
        internal static string lblCreateItems {
            get {
                return ResourceManager.GetString("lblCreateItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء الحجم.
        /// </summary>
        internal static string lblCreateSize {
            get {
                return ResourceManager.GetString("lblCreateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء متجر.
        /// </summary>
        internal static string lblCreateStore {
            get {
                return ResourceManager.GetString("lblCreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء نوع فرعي.
        /// </summary>
        internal static string lblCreateSubType {
            get {
                return ResourceManager.GetString("lblCreateSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء نوع.
        /// </summary>
        internal static string lblCreateType {
            get {
                return ResourceManager.GetString("lblCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء وحدة.
        /// </summary>
        internal static string lblCreateUnit {
            get {
                return ResourceManager.GetString("lblCreateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد العميل:.
        /// </summary>
        internal static string lblCustomerBalance {
            get {
                return ResourceManager.GetString("lblCustomerBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هوية العميل:.
        /// </summary>
        internal static string lblCustomerId {
            get {
                return ResourceManager.GetString("lblCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        internal static string lblCustomerName {
            get {
                return ResourceManager.GetString("lblCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العميل.
        /// </summary>
        internal static string lblCustomerType {
            get {
                return ResourceManager.GetString("lblCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء.
        /// </summary>
        internal static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من التاريخ:.
        /// </summary>
        internal static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الاجمالي.
        /// </summary>
        internal static string lblGrandAmount {
            get {
                return ResourceManager.GetString("lblGrandAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتوره.
        /// </summary>
        internal static string lblInvoiceNumber {
            get {
                return ResourceManager.GetString("lblInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صنف باركود.
        /// </summary>
        internal static string lblItemBarcode {
            get {
                return ResourceManager.GetString("lblItemBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الصنف.
        /// </summary>
        internal static string lblItemID {
            get {
                return ResourceManager.GetString("lblItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصنف.
        /// </summary>
        internal static string lblItemName {
            get {
                return ResourceManager.GetString("lblItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الصنف.
        /// </summary>
        internal static string lblItemSize {
            get {
                return ResourceManager.GetString("lblItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العنصر الفرعي.
        /// </summary>
        internal static string lblItemSubType {
            get {
                return ResourceManager.GetString("lblItemSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العنصر.
        /// </summary>
        internal static string lblItemType {
            get {
                return ResourceManager.GetString("lblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدة البند.
        /// </summary>
        internal static string lblItemUnit {
            get {
                return ResourceManager.GetString("lblItemUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع.
        /// </summary>
        internal static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المندوب.
        /// </summary>
        internal static string lblNameVendor {
            get {
                return ResourceManager.GetString("lblNameVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الصافي.
        /// </summary>
        internal static string lblNetAmount {
            get {
                return ResourceManager.GetString("lblNetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المالك.
        /// </summary>
        internal static string lblOwnerName {
            get {
                return ResourceManager.GetString("lblOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المدفوع.
        /// </summary>
        internal static string lblPaidAmount {
            get {
                return ResourceManager.GetString("lblPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمه السر.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الدفع.
        /// </summary>
        internal static string lblPaymentType {
            get {
                return ResourceManager.GetString("lblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        internal static string lblPhoneNo {
            get {
                return ResourceManager.GetString("lblPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطعة في حزمة:.
        /// </summary>
        internal static string lblPieceInPack {
            get {
                return ResourceManager.GetString("lblPieceInPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتوره.
        /// </summary>
        internal static string lblPurchaseInvoiceNo {
            get {
                return ResourceManager.GetString("lblPurchaseInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشراء.
        /// </summary>
        internal static string lblPurchasePrice {
            get {
                return ResourceManager.GetString("lblPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الذي تسلمه:.
        /// </summary>
        internal static string lblReceivedAmount {
            get {
                return ResourceManager.GetString("lblReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريج. اسم العميل:.
        /// </summary>
        internal static string lblRegCustomerName {
            get {
                return ResourceManager.GetString("lblRegCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل منتظم.
        /// </summary>
        internal static string lblRegularCustomer {
            get {
                return ResourceManager.GetString("lblRegularCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المندوب منتظم.
        /// </summary>
        internal static string lblRegularVendor {
            get {
                return ResourceManager.GetString("lblRegularVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة المبيعات.
        /// </summary>
        internal static string lblSalesInvoice {
            get {
                return ResourceManager.GetString("lblSalesInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح الباركود هنا.
        /// </summary>
        internal static string lblScanBarcode {
            get {
                return ResourceManager.GetString("lblScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ المحل:.
        /// </summary>
        internal static string lblShopAmount {
            get {
                return ResourceManager.GetString("lblShopAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الحجم.
        /// </summary>
        internal static string lblSizeID {
            get {
                return ResourceManager.GetString("lblSizeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحجم.
        /// </summary>
        internal static string lblSizeName {
            get {
                return ResourceManager.GetString("lblSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر البيع بدون ضريبة.
        /// </summary>
        internal static string lblSPWOT {
            get {
                return ResourceManager.GetString("lblSPWOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر البيع مع الضريبة.
        /// </summary>
        internal static string lblSPWT {
            get {
                return ResourceManager.GetString("lblSPWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستوى الحرج للمخزون:.
        /// </summary>
        internal static string lblStockCriticalLevel {
            get {
                return ResourceManager.GetString("lblStockCriticalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف المتجر.
        /// </summary>
        internal static string lblStoreID {
            get {
                return ResourceManager.GetString("lblStoreID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعار المتجر.
        /// </summary>
        internal static string lblStoreLogo {
            get {
                return ResourceManager.GetString("lblStoreLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المتجر.
        /// </summary>
        internal static string lblStoreName {
            get {
                return ResourceManager.GetString("lblStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف النوع الفرعي.
        /// </summary>
        internal static string lblSubTypeID {
            get {
                return ResourceManager.GetString("lblSubTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم النوع الفرعي.
        /// </summary>
        internal static string lblSubTypeName {
            get {
                return ResourceManager.GetString("lblSubTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ٪ الضريبة.
        /// </summary>
        internal static string lblTax {
            get {
                return ResourceManager.GetString("lblTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الضريبة:.
        /// </summary>
        internal static string lblTaxAmount {
            get {
                return ResourceManager.GetString("lblTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الضريبة:.
        /// </summary>
        internal static string lblTaxNumber {
            get {
                return ResourceManager.GetString("lblTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حتى الآن:.
        /// </summary>
        internal static string lblToDate {
            get {
                return ResourceManager.GetString("lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكتب معرف.
        /// </summary>
        internal static string lblTypeID {
            get {
                return ResourceManager.GetString("lblTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم نوع.
        /// </summary>
        internal static string lblTypeName {
            get {
                return ResourceManager.GetString("lblTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف الوحدة.
        /// </summary>
        internal static string lblUnitID {
            get {
                return ResourceManager.GetString("lblUnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم الوحدة.
        /// </summary>
        internal static string lblUnitName {
            get {
                return ResourceManager.GetString("lblUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم:.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم االمستخدم.
        /// </summary>
        internal static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيد المندوب:.
        /// </summary>
        internal static string lblVendorBalance {
            get {
                return ResourceManager.GetString("lblVendorBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز البائع.
        /// </summary>
        internal static string lblVendorCode {
            get {
                return ResourceManager.GetString("lblVendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف البائع.
        /// </summary>
        internal static string lblVendorID {
            get {
                return ResourceManager.GetString("lblVendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المندوب.
        /// </summary>
        internal static string lblVendorName {
            get {
                return ResourceManager.GetString("lblVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الباقة.
        /// </summary>
        internal static string PackPrice {
            get {
                return ResourceManager.GetString("PackPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الذي تسلمه.
        /// </summary>
        internal static string Recievd_Amount {
            get {
                return ResourceManager.GetString("Recievd_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عام.
        /// </summary>
        internal static string rp1 {
            get {
                return ResourceManager.GetString("rp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير المبيعات.
        /// </summary>
        internal static string rp2 {
            get {
                return ResourceManager.GetString("rp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المخزون.
        /// </summary>
        internal static string rp3 {
            get {
                return ResourceManager.GetString("rp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقارير.
        /// </summary>
        internal static string rp4 {
            get {
                return ResourceManager.GetString("rp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السيطرة الامنية.
        /// </summary>
        internal static string rpg1 {
            get {
                return ResourceManager.GetString("rpg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجهزة العامة.
        /// </summary>
        internal static string rpg2 {
            get {
                return ResourceManager.GetString("rpg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الأصناف.
        /// </summary>
        internal static string rpg3 {
            get {
                return ResourceManager.GetString("rpg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملية فاتورة المبيعات.
        /// </summary>
        internal static string rpg4 {
            get {
                return ResourceManager.GetString("rpg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المخزون.
        /// </summary>
        internal static string rpg5 {
            get {
                return ResourceManager.GetString("rpg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير الأصناف.
        /// </summary>
        internal static string rpg6 {
            get {
                return ResourceManager.GetString("rpg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقرير المبيعات.
        /// </summary>
        internal static string rpg7 {
            get {
                return ResourceManager.GetString("rpg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقارير المخزون.
        /// </summary>
        internal static string rpg8 {
            get {
                return ResourceManager.GetString("rpg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير الشراء.
        /// </summary>
        internal static string rppurchase {
            get {
                return ResourceManager.GetString("rppurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف العميل.
        /// </summary>
        internal static string tabCustomer {
            get {
                return ResourceManager.GetString("tabCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف المتجر.
        /// </summary>
        internal static string tabStore {
            get {
                return ResourceManager.GetString("tabStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف المندوب.
        /// </summary>
        internal static string tabVendor {
            get {
                return ResourceManager.GetString("tabVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ.
        /// </summary>
        internal static string TPHistory {
            get {
                return ResourceManager.GetString("TPHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضف اصنف.
        /// </summary>
        internal static string TPItems {
            get {
                return ResourceManager.GetString("TPItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة المشتريات.
        /// </summary>
        internal static string TPPurchaseInvoice {
            get {
                return ResourceManager.GetString("TPPurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة الحجم.
        /// </summary>
        internal static string TPSize {
            get {
                return ResourceManager.GetString("TPSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع الفرعي.
        /// </summary>
        internal static string TPSubType {
            get {
                return ResourceManager.GetString("TPSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليوم بيع.
        /// </summary>
        internal static string TPTodaySale {
            get {
                return ResourceManager.GetString("TPTodaySale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة نوع.
        /// </summary>
        internal static string TPType {
            get {
                return ResourceManager.GetString("TPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وحدة.
        /// </summary>
        internal static string TPUnit {
            get {
                return ResourceManager.GetString("TPUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to س ر.
        /// </summary>
        internal static string TxtCR_Number {
            get {
                return ResourceManager.GetString("TxtCR_Number", resourceCulture);
            }
        }
    }
}
