//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Software.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS_Software.Globalization.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Detail.
        /// </summary>
        internal static string brnSaleDetail {
            get {
                return ResourceManager.GetString("brnSaleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string btnAddCustomer {
            get {
                return ResourceManager.GetString("btnAddCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor.
        /// </summary>
        internal static string btnAddVendor {
            get {
                return ResourceManager.GetString("btnAddVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Assign.
        /// </summary>
        internal static string BtnAssignUnits {
            get {
                return ResourceManager.GetString("BtnAssignUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        internal static string btnBetween {
            get {
                return ResourceManager.GetString("btnBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Your Store.
        /// </summary>
        internal static string btnCreateStore {
            get {
                return ResourceManager.GetString("btnCreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        internal static string btnCreateUser {
            get {
                return ResourceManager.GetString("btnCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string btnFind {
            get {
                return ResourceManager.GetString("btnFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Detail.
        /// </summary>
        internal static string btnInvoiceDetail {
            get {
                return ResourceManager.GetString("btnInvoiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Bracode.
        /// </summary>
        internal static string btnItemsBarcode {
            get {
                return ResourceManager.GetString("btnItemsBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items SubType.
        /// </summary>
        internal static string btnItemsCategory {
            get {
                return ResourceManager.GetString("btnItemsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Definition.
        /// </summary>
        internal static string btnItemsdefinition {
            get {
                return ResourceManager.GetString("btnItemsdefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Item Size.
        /// </summary>
        internal static string btnItemsSize {
            get {
                return ResourceManager.GetString("btnItemsSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Items Type.
        /// </summary>
        internal static string btnItemsType {
            get {
                return ResourceManager.GetString("btnItemsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Items Unit.
        /// </summary>
        internal static string btnItemsUnit {
            get {
                return ResourceManager.GetString("btnItemsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Detail.
        /// </summary>
        internal static string btnRptItemsDetail {
            get {
                return ResourceManager.GetString("btnRptItemsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sale Invoice.
        /// </summary>
        internal static string btnSales {
            get {
                return ResourceManager.GetString("btnSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice Return.
        /// </summary>
        internal static string btnSalesReturns {
            get {
                return ResourceManager.GetString("btnSalesReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Assign.
        /// </summary>
        internal static string btnSizeAssign {
            get {
                return ResourceManager.GetString("btnSizeAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Stock.
        /// </summary>
        internal static string BtnStock {
            get {
                return ResourceManager.GetString("BtnStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Detail.
        /// </summary>
        internal static string btnStockDetail {
            get {
                return ResourceManager.GetString("btnStockDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock in Detail.
        /// </summary>
        internal static string btnStockInDetail {
            get {
                return ResourceManager.GetString("btnStockInDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Out Detail.
        /// </summary>
        internal static string btnStockOutDetail {
            get {
                return ResourceManager.GetString("btnStockOutDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string btnToday {
            get {
                return ResourceManager.GetString("btnToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define User Role.
        /// </summary>
        internal static string btnUserRole {
            get {
                return ResourceManager.GetString("btnUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string btnYesterday {
            get {
                return ResourceManager.GetString("btnYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CkEActive {
            get {
                return ResourceManager.GetString("CkEActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packed.
        /// </summary>
        internal static string CkEIsPacked {
            get {
                return ResourceManager.GetString("CkEIsPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string Created_By {
            get {
                return ResourceManager.GetString("Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Definition.
        /// </summary>
        internal static string frmCustomerDeffination {
            get {
                return ResourceManager.GetString("frmCustomerDeffination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Definition.
        /// </summary>
        internal static string frmItems_Deffination {
            get {
                return ResourceManager.GetString("frmItems_Deffination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice.
        /// </summary>
        internal static string frmPurchaseInvoices {
            get {
                return ResourceManager.GetString("frmPurchaseInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice.
        /// </summary>
        internal static string frmSalesInvoices {
            get {
                return ResourceManager.GetString("frmSalesInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Size.
        /// </summary>
        internal static string frmSizAssigns {
            get {
                return ResourceManager.GetString("frmSizAssigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Your Store.
        /// </summary>
        internal static string frmStore_Deffination {
            get {
                return ResourceManager.GetString("frmStore_Deffination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Type.
        /// </summary>
        internal static string frmSubtype {
            get {
                return ResourceManager.GetString("frmSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string frmTypes {
            get {
                return ResourceManager.GetString("frmTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Assign.
        /// </summary>
        internal static string frmUnitAssign {
            get {
                return ResourceManager.GetString("frmUnitAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string frmUnits {
            get {
                return ResourceManager.GetString("frmUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Box.
        /// </summary>
        internal static string gPaymentBox {
            get {
                return ResourceManager.GetString("gPaymentBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total.
        /// </summary>
        internal static string Grand_Total {
            get {
                return ResourceManager.GetString("Grand_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Date.
        /// </summary>
        internal static string Invoice_Date {
            get {
                return ResourceManager.GetString("Invoice_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Item_Amount {
            get {
                return ResourceManager.GetString("Item_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string Item_Barcode {
            get {
                return ResourceManager.GetString("Item_Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        internal static string Item_Sale_Price {
            get {
                return ResourceManager.GetString("Item_Sale_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Size.
        /// </summary>
        internal static string lblAssignSize {
            get {
                return ResourceManager.GetString("lblAssignSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Unit.
        /// </summary>
        internal static string lblAssignUnit {
            get {
                return ResourceManager.GetString("lblAssignUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        internal static string lblBalance {
            get {
                return ResourceManager.GetString("lblBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack/Bundle Price:.
        /// </summary>
        internal static string lblBundlePrice {
            get {
                return ResourceManager.GetString("lblBundlePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque/Card No.:.
        /// </summary>
        internal static string lblCardNo {
            get {
                return ResourceManager.GetString("lblCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name:.
        /// </summary>
        internal static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Number.
        /// </summary>
        internal static string lblCellNo {
            get {
                return ResourceManager.GetString("lblCellNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code/Cell Number:.
        /// </summary>
        internal static string lblCodeNo {
            get {
                return ResourceManager.GetString("lblCodeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number:.
        /// </summary>
        internal static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Items.
        /// </summary>
        internal static string lblCreateItems {
            get {
                return ResourceManager.GetString("lblCreateItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Size.
        /// </summary>
        internal static string lblCreateSize {
            get {
                return ResourceManager.GetString("lblCreateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Store.
        /// </summary>
        internal static string lblCreateStore {
            get {
                return ResourceManager.GetString("lblCreateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SubTye.
        /// </summary>
        internal static string lblCreateSubType {
            get {
                return ResourceManager.GetString("lblCreateSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Type.
        /// </summary>
        internal static string lblCreateType {
            get {
                return ResourceManager.GetString("lblCreateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Unit.
        /// </summary>
        internal static string lblCreateUnit {
            get {
                return ResourceManager.GetString("lblCreateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Balance:.
        /// </summary>
        internal static string lblCustomerBalance {
            get {
                return ResourceManager.GetString("lblCustomerBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID:.
        /// </summary>
        internal static string lblCustomerId {
            get {
                return ResourceManager.GetString("lblCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name:.
        /// </summary>
        internal static string lblCustomerName {
            get {
                return ResourceManager.GetString("lblCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type:.
        /// </summary>
        internal static string lblCustomerType {
            get {
                return ResourceManager.GetString("lblCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date:.
        /// </summary>
        internal static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date:.
        /// </summary>
        internal static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Amount:.
        /// </summary>
        internal static string lblGrandAmount {
            get {
                return ResourceManager.GetString("lblGrandAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number:.
        /// </summary>
        internal static string lblInvoiceNumber {
            get {
                return ResourceManager.GetString("lblInvoiceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Barcode:.
        /// </summary>
        internal static string lblItemBarcode {
            get {
                return ResourceManager.GetString("lblItemBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ID:.
        /// </summary>
        internal static string lblItemID {
            get {
                return ResourceManager.GetString("lblItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name:.
        /// </summary>
        internal static string lblItemName {
            get {
                return ResourceManager.GetString("lblItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Size:.
        /// </summary>
        internal static string lblItemSize {
            get {
                return ResourceManager.GetString("lblItemSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item SubType:.
        /// </summary>
        internal static string lblItemSubType {
            get {
                return ResourceManager.GetString("lblItemSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Type:.
        /// </summary>
        internal static string lblItemType {
            get {
                return ResourceManager.GetString("lblItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Unit:.
        /// </summary>
        internal static string lblItemUnit {
            get {
                return ResourceManager.GetString("lblItemUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string lblLocation {
            get {
                return ResourceManager.GetString("lblLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Vendor.
        /// </summary>
        internal static string lblNameVendor {
            get {
                return ResourceManager.GetString("lblNameVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Amount:.
        /// </summary>
        internal static string lblNetAmount {
            get {
                return ResourceManager.GetString("lblNetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name:.
        /// </summary>
        internal static string lblOwnerName {
            get {
                return ResourceManager.GetString("lblOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount:.
        /// </summary>
        internal static string lblPaidAmount {
            get {
                return ResourceManager.GetString("lblPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type:.
        /// </summary>
        internal static string lblPaymentType {
            get {
                return ResourceManager.GetString("lblPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number:.
        /// </summary>
        internal static string lblPhoneNo {
            get {
                return ResourceManager.GetString("lblPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piece in Pack:.
        /// </summary>
        internal static string lblPieceInPack {
            get {
                return ResourceManager.GetString("lblPieceInPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number:.
        /// </summary>
        internal static string lblPurchaseInvoiceNo {
            get {
                return ResourceManager.GetString("lblPurchaseInvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price:.
        /// </summary>
        internal static string lblPurchasePrice {
            get {
                return ResourceManager.GetString("lblPurchasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Amount:.
        /// </summary>
        internal static string lblReceivedAmount {
            get {
                return ResourceManager.GetString("lblReceivedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. Customer Name:.
        /// </summary>
        internal static string lblRegCustomerName {
            get {
                return ResourceManager.GetString("lblRegCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Customer.
        /// </summary>
        internal static string lblRegularCustomer {
            get {
                return ResourceManager.GetString("lblRegularCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Vendor.
        /// </summary>
        internal static string lblRegularVendor {
            get {
                return ResourceManager.GetString("lblRegularVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice.
        /// </summary>
        internal static string lblSalesInvoice {
            get {
                return ResourceManager.GetString("lblSalesInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Barcode Here:.
        /// </summary>
        internal static string lblScanBarcode {
            get {
                return ResourceManager.GetString("lblScanBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Amount:.
        /// </summary>
        internal static string lblShopAmount {
            get {
                return ResourceManager.GetString("lblShopAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size ID:.
        /// </summary>
        internal static string lblSizeID {
            get {
                return ResourceManager.GetString("lblSizeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size Name:.
        /// </summary>
        internal static string lblSizeName {
            get {
                return ResourceManager.GetString("lblSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price Without Tax:.
        /// </summary>
        internal static string lblSPWOT {
            get {
                return ResourceManager.GetString("lblSPWOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Price With Tax:.
        /// </summary>
        internal static string lblSPWT {
            get {
                return ResourceManager.GetString("lblSPWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Critical Level:.
        /// </summary>
        internal static string lblStockCriticalLevel {
            get {
                return ResourceManager.GetString("lblStockCriticalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store ID:.
        /// </summary>
        internal static string lblStoreID {
            get {
                return ResourceManager.GetString("lblStoreID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Logo.
        /// </summary>
        internal static string lblStoreLogo {
            get {
                return ResourceManager.GetString("lblStoreLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name:.
        /// </summary>
        internal static string lblStoreName {
            get {
                return ResourceManager.GetString("lblStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubType ID:.
        /// </summary>
        internal static string lblSubTypeID {
            get {
                return ResourceManager.GetString("lblSubTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTyp Name:.
        /// </summary>
        internal static string lblSubTypeName {
            get {
                return ResourceManager.GetString("lblSubTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax %.
        /// </summary>
        internal static string lblTax {
            get {
                return ResourceManager.GetString("lblTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount:.
        /// </summary>
        internal static string lblTaxAmount {
            get {
                return ResourceManager.GetString("lblTaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number:.
        /// </summary>
        internal static string lblTaxNumber {
            get {
                return ResourceManager.GetString("lblTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date:.
        /// </summary>
        internal static string lblToDate {
            get {
                return ResourceManager.GetString("lblToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type ID:.
        /// </summary>
        internal static string lblTypeID {
            get {
                return ResourceManager.GetString("lblTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name:.
        /// </summary>
        internal static string lblTypeName {
            get {
                return ResourceManager.GetString("lblTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit ID:.
        /// </summary>
        internal static string lblUnitID {
            get {
                return ResourceManager.GetString("lblUnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name:.
        /// </summary>
        internal static string lblUnitName {
            get {
                return ResourceManager.GetString("lblUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Balance:.
        /// </summary>
        internal static string lblVendorBalance {
            get {
                return ResourceManager.GetString("lblVendorBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Code:.
        /// </summary>
        internal static string lblVendorCode {
            get {
                return ResourceManager.GetString("lblVendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor ID:.
        /// </summary>
        internal static string lblVendorID {
            get {
                return ResourceManager.GetString("lblVendorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEndor Name:.
        /// </summary>
        internal static string lblVendorName {
            get {
                return ResourceManager.GetString("lblVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Price.
        /// </summary>
        internal static string PackPrice {
            get {
                return ResourceManager.GetString("PackPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Amount.
        /// </summary>
        internal static string Recievd_Amount {
            get {
                return ResourceManager.GetString("Recievd_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string rp1 {
            get {
                return ResourceManager.GetString("rp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoices.
        /// </summary>
        internal static string rp2 {
            get {
                return ResourceManager.GetString("rp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Management.
        /// </summary>
        internal static string rp3 {
            get {
                return ResourceManager.GetString("rp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string rp4 {
            get {
                return ResourceManager.GetString("rp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Control.
        /// </summary>
        internal static string rpg1 {
            get {
                return ResourceManager.GetString("rpg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Setups.
        /// </summary>
        internal static string rpg2 {
            get {
                return ResourceManager.GetString("rpg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Management.
        /// </summary>
        internal static string rpg3 {
            get {
                return ResourceManager.GetString("rpg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice Process.
        /// </summary>
        internal static string rpg4 {
            get {
                return ResourceManager.GetString("rpg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Management.
        /// </summary>
        internal static string rpg5 {
            get {
                return ResourceManager.GetString("rpg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Reports.
        /// </summary>
        internal static string rpg6 {
            get {
                return ResourceManager.GetString("rpg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Reports.
        /// </summary>
        internal static string rpg7 {
            get {
                return ResourceManager.GetString("rpg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Reports.
        /// </summary>
        internal static string rpg8 {
            get {
                return ResourceManager.GetString("rpg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoices.
        /// </summary>
        internal static string rppurchase {
            get {
                return ResourceManager.GetString("rppurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string tabCustomer {
            get {
                return ResourceManager.GetString("tabCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Store.
        /// </summary>
        internal static string tabStore {
            get {
                return ResourceManager.GetString("tabStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Vendor.
        /// </summary>
        internal static string tabVendor {
            get {
                return ResourceManager.GetString("tabVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string TPHistory {
            get {
                return ResourceManager.GetString("TPHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items.
        /// </summary>
        internal static string TPItems {
            get {
                return ResourceManager.GetString("TPItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice.
        /// </summary>
        internal static string TPPurchaseInvoice {
            get {
                return ResourceManager.GetString("TPPurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Size.
        /// </summary>
        internal static string TPSize {
            get {
                return ResourceManager.GetString("TPSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SubType.
        /// </summary>
        internal static string TPSubType {
            get {
                return ResourceManager.GetString("TPSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Sale.
        /// </summary>
        internal static string TPTodaySale {
            get {
                return ResourceManager.GetString("TPTodaySale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Type.
        /// </summary>
        internal static string TPType {
            get {
                return ResourceManager.GetString("TPType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unit.
        /// </summary>
        internal static string TPUnit {
            get {
                return ResourceManager.GetString("TPUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Number.
        /// </summary>
        internal static string TxtCR_Number {
            get {
                return ResourceManager.GetString("TxtCR_Number", resourceCulture);
            }
        }
    }
}
