// <auto-generated />
//-----------------------------------------------------------------------
// <copyright file="frmMDI.cs" company="Calrom Limited">
// Copyright (c) Calrom Limited. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

namespace POS_Software
{
    using DevExpress.LookAndFeel;
    using DevExpress.Skins;
    using DevExpress.XtraBars;
    using DevExpress.XtraEditors;
    using DevExpress.XtraTab;
    using POS_Software.Modules;
    using System;
    using System.Data;
    using System.Globalization;
    using System.Resources;
    using System.Windows.Forms;

    /// <summary>
    /// Defines the <see cref="frmMDI" />.
    /// </summary>
    public partial class frmMDI : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        /// <summary>
        /// Defines the Restart.
        /// </summary>
        private Boolean Restart = false;

        /// <summary>
        /// Defines the resourceManager.
        /// </summary>
        private ResourceManager resourceManager;

        /// <summary>
        /// Defines the culture.
        /// </summary>
        private CultureInfo culture;

        /// <summary>
        /// Initializes a new instance of the <see cref="frmMDI"/> class.
        /// </summary>
        public frmMDI()
        {
            InitializeComponent();
            InitSkinGallery();
            UserLookAndFeel.Default.SetSkinStyle("Caramel");
            //UserLookAndFeel.Default.SetSkinStyle("Seven");
        }

        /// <summary>
        /// The InitSkinGallery.
        /// </summary>
        public void InitSkinGallery()
        {
            DevExpress.XtraBars.Helpers.SkinHelper.InitSkinGallery(Skins, true);
            SkinManager.EnableFormSkins();
            LookAndFeelHelper.ForceDefaultLookAndFeelChanged();
            SkinManager.EnableMdiFormSkins();
        }

        /// <summary>
        /// The frmMDI_FormClosed.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="FormClosedEventArgs"/>.</param>
        private void frmMDI_FormClosed(object sender, FormClosedEventArgs e)
        {
            if (!Restart)
                Application.Exit();
        }

        /// <summary>
        /// The frmMDI_FormClosing.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="FormClosingEventArgs"/>.</param>
        private void frmMDI_FormClosing(object sender, FormClosingEventArgs e)
        {
            if (!Restart)
                if (XtraMessageBox.Show("Are you sure that you would like to close this application?", "Application Closing", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.No)
                    e.Cancel = true;
        }

        /// <summary>
        /// The Frm_Mdi_Load.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="EventArgs"/>.</param>
        private void Frm_Mdi_Load(object sender, EventArgs e)
        {
            MdiClient ctlMDI;
            foreach (Control ctl in this.Controls)
            {
                try
                {
                    ctlMDI = (MdiClient)ctl;

                    ctlMDI.BackColor = this.BackColor;
                }
                catch (InvalidCastException exc)
                {
                    // Catch and ignore the error if casting failed.
                }

            }
            if (Modules.General.userrole != "admin")
            {
                DataTable dtsecurity = new DataTable();
                dtsecurity = DalHandlar.RunQuery("Select * from admin.userrights");
                rp1.Visible = Convert.ToBoolean(dtsecurity.Rows[0]["isactive"]);
                rp2.Visible = Convert.ToBoolean(dtsecurity.Rows[1]["isactive"]);
                rp3.Visible = Convert.ToBoolean(dtsecurity.Rows[2]["isactive"]);
                rp4.Visible = Convert.ToBoolean(dtsecurity.Rows[3]["isactive"]);
                rpg1.Visible = Convert.ToBoolean(dtsecurity.Rows[4]["isactive"]);
                rpg2.Visible = Convert.ToBoolean(dtsecurity.Rows[5]["isactive"]);
                rpg3.Visible = Convert.ToBoolean(dtsecurity.Rows[6]["isactive"]);
                rpg4.Visible = Convert.ToBoolean(dtsecurity.Rows[7]["isactive"]);
                rpg5.Visible = Convert.ToBoolean(dtsecurity.Rows[8]["isactive"]);
                rpg6.Visible = Convert.ToBoolean(dtsecurity.Rows[9]["isactive"]);
                rpg7.Visible = Convert.ToBoolean(dtsecurity.Rows[10]["isactive"]);
                rpg8.Visible = Convert.ToBoolean(dtsecurity.Rows[11]["isactive"]);
                rppurchase.Visible = Convert.ToBoolean(dtsecurity.Rows[12]["isactive"]);
                btnAddCustomer.Enabled = Convert.ToBoolean(dtsecurity.Rows[13]["isactive"]);
                brnSaleDetail.Enabled = Convert.ToBoolean(dtsecurity.Rows[14]["isactive"]);
                BtnAssignUnits.Enabled = Convert.ToBoolean(dtsecurity.Rows[15]["isactive"]);
                btnCreateStore.Enabled = Convert.ToBoolean(dtsecurity.Rows[16]["isactive"]);
                btnCreateUser.Enabled = Convert.ToBoolean(dtsecurity.Rows[17]["isactive"]);
                btnInvoiceDetail.Enabled = Convert.ToBoolean(dtsecurity.Rows[18]["isactive"]);
                btnItemsBarcode.Enabled = Convert.ToBoolean(dtsecurity.Rows[19]["isactive"]);
                btnItemsCategory.Enabled = Convert.ToBoolean(dtsecurity.Rows[20]["isactive"]);
                btnItemsdefinition.Enabled = Convert.ToBoolean(dtsecurity.Rows[21]["isactive"]);
                btnItemsSize.Enabled = Convert.ToBoolean(dtsecurity.Rows[22]["isactive"]);
                btnItemsType.Enabled = Convert.ToBoolean(dtsecurity.Rows[23]["isactive"]);
                btnItemsUnit.Enabled = Convert.ToBoolean(dtsecurity.Rows[24]["isactive"]);
                btnRptItemsDetail.Enabled = Convert.ToBoolean(dtsecurity.Rows[25]["isactive"]);
                btnSales.Enabled = Convert.ToBoolean(dtsecurity.Rows[26]["isactive"]);
                btnSalesReturns.Enabled = Convert.ToBoolean(dtsecurity.Rows[27]["isactive"]);
                btnSizeAssign.Enabled = Convert.ToBoolean(dtsecurity.Rows[28]["isactive"]);
                BtnStock.Enabled = Convert.ToBoolean(dtsecurity.Rows[29]["isactive"]);
                btnStockDetail.Enabled = Convert.ToBoolean(dtsecurity.Rows[30]["isactive"]);
                btnStockInDetail.Enabled = Convert.ToBoolean(dtsecurity.Rows[31]["isactive"]);
                btnStockOutDetail.Enabled = Convert.ToBoolean(dtsecurity.Rows[32]["isactive"]);
                btnUserRole.Enabled = Convert.ToBoolean(dtsecurity.Rows[33]["isactive"]);
                btnaddvendor.Enabled = Convert.ToBoolean(dtsecurity.Rows[34]["isactive"]);
                btnPurchaseInvoice.Enabled = Convert.ToBoolean(dtsecurity.Rows[35]["isactive"]);


            }


            DataTable dtLanguage = new DataTable();
            dtLanguage.Columns.Add("Id", typeof(string));
            dtLanguage.Columns.Add("Language", typeof(string));

            dtLanguage.Rows.Add("ar", "Arabic");
            dtLanguage.Rows.Add("en", "English");

            rlueLanguage.DataSource = dtLanguage;
            rlueLanguage.DisplayMember = "Language";
            rlueLanguage.ValueMember = "Id";
        }

        /// <summary>
        /// The btnUserRole_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnUserRole_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.UserRole(this);
        }

        /// <summary>
        /// The btnCreateUser_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnCreateUser_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.CreateUser(this);
        }

        /// <summary>
        /// The btnItemsType_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnItemsType_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemsType(this);
        }

        /// <summary>
        /// The btnItemsCategory_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnItemsCategory_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemCategory(this);
        }

        /// <summary>
        /// The btnItemsSize_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnItemsSize_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemSize(this);
        }

        /// <summary>
        /// The btnItemsUnit_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnItemsUnit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemUnit(this);
        }

        /// <summary>
        /// The btnItemsdefinition_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnItemsdefinition_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemsDeffinition(this);
        }

        /// <summary>
        /// The btnItemsBarcode_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnItemsBarcode_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemsBarcode(this);
        }

        /// <summary>
        /// The ReportDisplay.
        /// </summary>
        /// <param name="Rpt">The Rpt<see cref="DevExpress.XtraReports.UI.XtraReport"/>.</param>
        /// <param name="dt">The dt<see cref="DataTable"/>.</param>
        public void ReportDisplay(DevExpress.XtraReports.UI.XtraReport Rpt, DataTable dt)
        {
            Soothmedia.Reports.WinForm.ShowXtraReport(this, Rpt, dt, Modules.Main.DateFormat,true);
        }
        public void ReportDisplay1(DevExpress.XtraReports.UI.XtraReport Rpt, DataTable dt)
        {
            Soothmedia.Reports.WinForm.ShowXtraReport(this, Rpt, dt, Modules.Main.DateFormat);
        }
        /// <summary>
        /// The btnSales_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnSales_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemSals(this);
        }

        /// <summary>
        /// The BtnStock_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void BtnStock_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.ItemStock(this);
        }

        /// <summary>
        /// The btnCreateStore_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnCreateStore_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.StoreDeff(this);
        }

        /// <summary>
        /// The btnSalesReturns_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraBars.ItemClickEventArgs"/>.</param>
        private void btnSalesReturns_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Forms.Form.SalesRetruns(this);
        }

        /// <summary>
        /// The TabActiveForm_Click.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="EventArgs"/>.</param>
        private void TabActiveForm_Click(object sender, EventArgs e)
        {
            (TabActiveForm.SelectedTabPage.Tag as Form).Select();
        }

        /// <summary>
        /// The TabActiveForm_SelectedPageChanged.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="DevExpress.XtraTab.TabPageChangedEventArgs"/>.</param>
        private void TabActiveForm_SelectedPageChanged(object sender, DevExpress.XtraTab.TabPageChangedEventArgs e)
        {
            if ((TabActiveForm.SelectedTabPage != null) && (TabActiveForm.SelectedTabPage.Tag != null))
            {
                (TabActiveForm.SelectedTabPage.Tag as Form).Select();
            }
            var strings = this.ActiveMdiChild.Name;
            if (strings == "frmReportViewer")
            {
                this.ActiveMdiChild.WindowState = FormWindowState.Maximized;
            }
        }

        /// <summary>
        /// The frmMDI_MdiChildActivate.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="EventArgs"/>.</param>
        private void frmMDI_MdiChildActivate(object sender, EventArgs e)
        {

            if (this.ActiveMdiChild == null)
                TabActiveForm.Visible = false;
            else
            {
                if (this.ActiveMdiChild.Tag == null)
                {
                    XtraTabPage tp = new XtraTabPage();
                    // if (this.ActiveMdiChild.Name != "frmReportViewer")
                    tp.Text = this.ActiveMdiChild.Text;
                    //if (this.ActiveMdiChild.Name == "frmReportViewer")
                    //    tp.Text = this.ActiveMdiChild.Tag.ToString();
                    TabActiveForm.TabPages.Add(tp);
                    tp.Tag = this.ActiveMdiChild;
                    tp.Parent = TabActiveForm;
                    TabActiveForm.SelectedTabPage = tp;
                    this.ActiveMdiChild.Tag = tp;
                    this.ActiveMdiChild.FormClosed += new FormClosedEventHandler(ActiveMdiChild_FormClosed);
                }
                if (!TabActiveForm.Visible) TabActiveForm.Visible = true;
            }
        }

        /// <summary>
        /// The ActiveMdiChild_FormClosed.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="FormClosedEventArgs"/>.</param>
        private void ActiveMdiChild_FormClosed(object sender, FormClosedEventArgs e)
        {
            ((sender as Form).Tag as XtraTabPage).Dispose();
        }

        /// <summary>
        /// The BtnAssignUnits_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void BtnAssignUnits_ItemClick(object sender, ItemClickEventArgs e)
        {

            Forms.Form.UnitsAssin(this);
        }

        /// <summary>
        /// The btnSizeAssign_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void btnSizeAssign_ItemClick(object sender, ItemClickEventArgs e)
        {
            Forms.Form.SizeAssign(this);
        }

        /// <summary>
        /// The btnRptItemsDetail_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void btnRptItemsDetail_ItemClick(object sender, ItemClickEventArgs e)
        {
            Reports.Report.ItemDetail(this);
        }

        /// <summary>
        /// The brnSaleDetail_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void brnSaleDetail_ItemClick(object sender, ItemClickEventArgs e)
        {
            Reports.Report.SalesDetail(this);
        }

        /// <summary>
        /// The btnInvoiceDetail_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void btnInvoiceDetail_ItemClick(object sender, ItemClickEventArgs e)
        {
            Reports.Report.InvoiceDetail(this);
        }

        /// <summary>
        /// The btnStockDetail_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void btnStockDetail_ItemClick(object sender, ItemClickEventArgs e)
        {
            Reports.Report.StockDetail(this);
        }

        /// <summary>
        /// The btnStockInDetail_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void btnStockInDetail_ItemClick(object sender, ItemClickEventArgs e)
        {
            Reports.Report.StockInDetail(this);
        }

        /// <summary>
        /// The btnStockOutDetail_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void btnStockOutDetail_ItemClick(object sender, ItemClickEventArgs e)
        {
            Reports.Report.StockOutDetail(this);
        }

        /// <summary>
        /// The btnAddCustomer_ItemClick.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="ItemClickEventArgs"/>.</param>
        private void btnAddCustomer_ItemClick(object sender, ItemClickEventArgs e)
        {
            //Forms.Form.AddCustomer(this);
        }

        /// <summary>
        /// The SwitchLanguage.
        /// </summary>
        private void SwitchLanguage()
        {
            rp1.Text = resourceManager.GetString("rp1", culture);
            rp2.Text = resourceManager.GetString("rp2", culture);
            rp3.Text = resourceManager.GetString("rp3", culture);
            rp4.Text = resourceManager.GetString("rp4", culture);

            rpg1.Text = resourceManager.GetString("rpg1", culture);
            rpg2.Text = resourceManager.GetString("rpg2", culture);
            rpg3.Text = resourceManager.GetString("rpg3", culture);
            rpg4.Text = resourceManager.GetString("rpg4", culture);
            rpg5.Text = resourceManager.GetString("rpg5", culture);
            rpg6.Text = resourceManager.GetString("rpg6", culture);
            rpg7.Text = resourceManager.GetString("rpg7", culture);
            rpg8.Text = resourceManager.GetString("rpg8", culture);
            rppurchase.Text = resourceManager.GetString("rppurchase", culture);

            btnAddCustomer.Caption = resourceManager.GetString("btnAddCustomer", culture);
            brnSaleDetail.Caption = resourceManager.GetString("brnSaleDetail", culture);
            BtnAssignUnits.Caption = resourceManager.GetString("BtnAssignUnits", culture);
            btnCreateStore.Caption = resourceManager.GetString("btnCreateStore", culture);
            btnCreateUser.Caption = resourceManager.GetString("btnCreateUser", culture);
            btnInvoiceDetail.Caption = resourceManager.GetString("btnInvoiceDetail", culture);
            btnItemsBarcode.Caption = resourceManager.GetString("btnItemsBarcode", culture);
            btnItemsCategory.Caption = resourceManager.GetString("btnItemsCategory", culture);
            btnItemsdefinition.Caption = resourceManager.GetString("btnItemsdefinition", culture);
            btnItemsSize.Caption = resourceManager.GetString("btnItemsSize", culture);
            btnItemsType.Caption = resourceManager.GetString("btnItemsType", culture);
            btnItemsUnit.Caption = resourceManager.GetString("btnItemsUnit", culture);
            btnRptItemsDetail.Caption = resourceManager.GetString("btnRptItemsDetail", culture);
            btnSales.Caption = resourceManager.GetString("btnSales", culture);
            btnSalesReturns.Caption = resourceManager.GetString("btnSalesReturns", culture);
            btnSizeAssign.Caption = resourceManager.GetString("btnSizeAssign", culture);
            BtnStock.Caption = resourceManager.GetString("BtnStock", culture);
            btnStockDetail.Caption = resourceManager.GetString("btnStockDetail", culture);
            btnStockInDetail.Caption = resourceManager.GetString("btnStockInDetail", culture);
            btnStockOutDetail.Caption = resourceManager.GetString("btnStockOutDetail", culture);
            btnUserRole.Caption = resourceManager.GetString("btnUserRole", culture);
            btnaddvendor.Caption = resourceManager.GetString("btnAddVendor", culture);
            btnPurchaseInvoice.Caption = resourceManager.GetString("TPPurchaseInvoice", culture);
        }

        /// <summary>
        /// The rlueLanguage_EditValueChanged.
        /// </summary>
        /// <param name="sender">The sender<see cref="object"/>.</param>
        /// <param name="e">The e<see cref="EventArgs"/>.</param>
        private void rlueLanguage_EditValueChanged(object sender, EventArgs e)
        {
            object value = (sender as LookUpEdit).EditValue;
            resourceManager = Convert.ToString(value).Equals("ar", StringComparison.OrdinalIgnoreCase) ?
                new ResourceManager("POS_Software.Globalization.Arabic", typeof(frmMDI).Assembly) :
                new ResourceManager("POS_Software.Globalization.English", typeof(frmMDI).Assembly);

            culture = CultureInfo.CreateSpecificCulture(Convert.ToString(value));
            General.resourceManager = resourceManager;
            General.culture = culture;
            SwitchLanguage();
        }

        private void ribbonControl1_Click(object sender, EventArgs e)
        {

        }

        private void btnaddvendor_ItemClick(object sender, ItemClickEventArgs e)
        {
           Forms.Form.AddVendor(this);
        }

        private void btnPurchaseInvoice_ItemClick(object sender, ItemClickEventArgs e)
        {
            Forms.Form.PurchaseInvoice(this);
        }

        private void btnAddCustomer_ItemClick_1(object sender, ItemClickEventArgs e)
        {
            Forms.Form.AddCustomer(this);
        }

        private void barButtonItem80_ItemClick(object sender, ItemClickEventArgs e)
        {
            Reports.Report.purhasereport(this);
        }

        private void bbtnVATReport_ItemClick(object sender, ItemClickEventArgs e)
        {
           Forms.Form.VATReport(this);
        }

        private void barButtonItem87_ItemClick(object sender, ItemClickEventArgs e)
        {
            Forms.Form.SalesPayment(this);
        }
    }
}
